version: "3.8"
services:
  postgres:
    image: library/postgres:13
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./postgres/:/docker-entrypoint-initdb.d/
    ports:
      - "5432:5432"

  store-service:
    build: ./modules/store-service
    image: romanowalex/store-service:v1.0-docker-remote-debug
    container_name: store-service
    environment:
      SPRING_PROFILES_ACTIVE: docker
    ports:
      - "8480:8480"
    depends_on:
      - postgres

  order-service:
    build:
      context: ./modules/order-service
      dockerfile: Dockerfile.docker-env
    image: romanowalex/order-service:v1.0-docker-remote-debug
    container_name: order-service
    environment:
      SPRING_PROFILES_ACTIVE: docker
    ports:
      - "8380:8380"
      - "5005:5005"
    depends_on:
      - postgres

  warehouse-service:
    build: ./modules/warehouse-service
    image: romanowalex/warehouse-service:v1.0-docker-remote-debug
    container_name: warehouse-service
    environment:
      SPRING_PROFILES_ACTIVE: docker
    ports:
      - "8280:8280"
    depends_on:
      - postgres

  warranty-service:
    build: ./modules/warranty-service
    image: romanowalex/warranty-service:v1.0-docker-remote-debug
    container_name: warranty-service
    environment:
      SPRING_PROFILES_ACTIVE: docker
    ports:
      - "8180:8180"
    depends_on:
      - postgres

volumes:
  db-data:
